Revert "Convert BubbleDataRepositoryTest to use mockito-kotlin"
error: frameworks/base/libs/WindowManager/Shell/tests/unittest/Android.bp:24:1: "WMShellUnitTests" depends on undefined module "mockito-kotlin2".
Or did you mean ["mockito-inline"]?

mockito-kotlin2 is defined in external/mockito-kotlin, but that
repository isn't tracked by the manifest.

This reverts commit 625a23ff22f0a9327b9a24341dfa0b8fbaf61a1b.

Change-Id: I8df76e1dc80d35427e2f0987a7dbb3088defba42